version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  assignees:
    - "deanwilson"
  reviewers:
    - "deanwilson"
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  assignees:
    - "deanwilson"
  reviewers:
    - "deanwilson"
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  assignees:
    - "deanwilson"
  reviewers:
    - "deanwilson"
