name: Rubocop linter

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Rubocop Linter
        uses: andrewmcodes/rubocop-linter-action@v3.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
